apiVersion: apps/v1
kind: Deployment
metadata:
  name: currencyconverter
  labels: { app: currencyconverter }
spec:
  replicas: 3
  selector:
    matchLabels: { app: currencyconverter }
  template:
    metadata:
      labels: { app: currencyconverter }
    spec:
      containers:
        - name: api
          image: your-registry/currencyconverter:latest
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_URLS
              value: "http://+:8080"
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"
          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 15
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
